
insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('12', null, null, '系统后台数据管理', null, null, null, '1');

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('2', '4028b881560c824a01560c9971450004', null, '菜单管理', '/his/public/menu-manager', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028866e53c553570153c555b2370000', '4028b881560c824a01560c9d00c10009', null, '号表维护', '/his/public/clinic-for-regist', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('402886225451b9b8015451c1733b0001', '4028b881560c824a01560c98ffe50003', null, '自定义菜单', '/his/public/wx_menu', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('402886225499134c01549916dcf80000', '4028b881560c824a01560c9c13db0008', null, '疾病维护', '/his/public/clinic-sickness', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('40288622558671f5015586745c5e0000', '4028b881560c824a01560c988e900002', null, '群发消息', '/his/public/send-all', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('40288622558ffa5301558ffd61500000', '4028b881560c824a01560c988e900002', null, '公众号消息及回复', '/his/public/message-manager', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde01545195c7f90002', '4028b881560c824a01560c9d00c10009', null, '号别维护', '/his/public/clinic-index', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde0154519159690000', '4028b881560c824a01560c9dce1a000a', null, '医生信息', '/his/public/doct-info-manager', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde01545197c56e0004', '4028b881560c824a01560c9a116b0005', null, '问卷维护', '/his/public/questionnaire-model', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde0154519660700003', '4028b881560c824a01560c9a116b0005', null, '问卷答题记录', '/his/public/answer-sheet', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde0154519871390005', '4028b881560c824a01560c9a116b0005', null, '问题维护', '/his/public/subject', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde015451994ade0006', '4028b881560c824a01560c9d00c10009', null, '号类维护', '/his/public/clinic-type-setting', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde0154519a24200007', '4028b881560c824a01560c9d00c10009', null, '出诊安排', '/his/public/clinic-schedule', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde0154519ada850008', '4028b881560c824a01560c9aad950006', null, '支付方式', '/his/public/pay-way-dict', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde0154519d1cdd000a', '4028b881560c824a01560c9aad950006', null, '基础信息', '/his/common/base-dict', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde0154519deaed000b', '4028b881560c824a01560c9dce1a000a', null, '医院概况', '/his/public/hospital-info', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('402886225580813b0155808d9bb60001', '40288622557b611d01557b6aaa730000', null, '图文素材', '/his/public/image-font-manager', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde0154519fac9e000d', '4028b881560c824a01560c9dce1a000a', null, '科室信息', '/his/public/dept-dict', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254517cde015451a0133b000e', '4028b881560c824a01560c9d00c10009', null, '门诊收费', '/his/public/clinic-type-charge', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('40288622549941280154995298380002', '4028b881560c824a01560c9c13db0008', null, '症状疾病维护', '/his/public/symptom-sickness', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('40288622559ec03a01559ec42fb40000', '4028b881560c824a01560c984cd50001', null, '关注用户维护', '/his/public/source-user', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('40288622557b611d01557b6aaa730000', '4028b881560c824a01560c97e0450000', null, '素材管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('40288622557b611d01557b88341a0001', '40288622557b611d01557b6aaa730000', null, '图片素材', '/his/public/image-manager', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254a2c4ec0154a2e4bce80000', '4028b881560c824a01560c9b7d0e0007', null, '就医问题维护', '/his/public/feed-back-target', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028862254b6e2c90154b6e7612c0000', '4028b881560c824a01560c9b7d0e0007', null, '反馈结果维护', '/his/public/feed-back-result', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c97e0450000', null, null, '微信端管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('402886225498950d015498a2a7590000', '4028b881560c824a01560c9c13db0008', null, '症状维护', '/his/public/clinic-symptom', null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c984cd50001', '4028b881560c824a01560c97e0450000', null, '关注用户管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c988e900002', '4028b881560c824a01560c97e0450000', null, '消息管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c98ffe50003', '4028b881560c824a01560c97e0450000', null, '菜单管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c9971450004', '1', null, '菜单管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c9a116b0005', '1', null, '调查问卷管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c9aad950006', '1', null, '基础字典管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c9b7d0e0007', '1', null, '就医反馈管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c9c13db0008', '1', null, '症状疾病管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c9d00c10009', '1', null, '号表管理', null, null, null, 1);

insert into MENU_DICT (ID, PARENT_ID, PARENT_IDS, MENU_NAME, HREF, ICON, SHOW_FLAG, POSITION)
values ('4028b881560c824a01560c9dce1a000a', '1', null, '医生科室医院管理', null, null, null, 1);
