
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028862255ed11490155ed3a7fd70004', null, null, null, 'DAY_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e9447d0153e94e59e90001', '1', '门诊', 'mz', 'DEPT_OUTP_INP_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e9447d0153e94e59eb0002', '0', '住院', 'zy', 'DEPT_OUTP_INP_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e961620153e96319820000', '1', '否', 'f', 'STOP_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e961620153e96319890001', '0', '是', 's', 'STOP_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e961620153e96524840003', '0', '否', 'f', 'END_DEPT_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e961620153e96524830002', '1', '是', 's', 'END_DEPT_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e961620153e966b66e0004', '1', '医疗技术类科室', 'yljslks', 'DEPT_TYPE_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e961620153e966b66f0005', '2', '医疗辅助类科室', 'ylfzlks', 'DEPT_TYPE_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e961620153e966b6720006', '3', '管理类科室', 'gllks', 'DEPT_TYPE_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e961620153e96ecd4b0007', '1', '经营科室', 'jyks', 'DEPT_CLASS_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028860853e961620153e96ecd4d0008', '0', '其他', 'qt', 'DEPT_CLASS_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9ecdc0006', '星期日', '星期日', 'xqr', 'DAY_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9ecd60005', '星期六', '星期六', 'xql', 'DAY_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9eccd0004', '星期五', '星期五', 'xqw', 'DAY_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9ecc90003', '星期四', '星期四', 'xqs', 'DAY_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9ecdd0007', '上午', '上午', 'sw', 'TIME_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9ece00008', '下午', '下午', 'xw', 'TIME_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9ece50009', '全天', '全天', 'qt', 'TIME_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9ece9000a', '夜间', '页面', 'ym', 'TIME_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9ec5b0000', '星期一', '星期一', 'xqy', 'DAY_FLAG');
insert into BASE_DICT (id, base_code, base_name, input_code, base_type)
values ('4028864653d097e40153d0a9ecba0001', '星期二', '星期二', 'xqe', 'DAY_FLAG');

